import React, { createContext, useContext, useState, useEffect } from 'react';
import { fetchVehicles } from '../../services/fleetApi';

const RoleContext = createContext();

export function RoleProvider({ children }) {
  const [currentUser, setCurrentUser] = useState(() => {
    const saved = localStorage.getItem("safeway_user");
    return saved ? JSON.parse(saved) : { role: "admin", name: "Fleet Supervisor", vehicleId: null };
  });

  const [registeredVehicles, setRegisteredVehicles] = useState([]);

  useEffect(() => {
    fetchVehicles().then(res => {
      if (res?.vehicles) setRegisteredVehicles(res.vehicles);
    });
  }, []);

  const loginAdmin = (username, password) => {
    if (username.trim().toLowerCase() === "admin" && password === "admin123") {
      const user = { role: "admin", name: "Mining Fleet Supervisor", vehicleId: null };
      setCurrentUser(user);
      localStorage.setItem("safeway_user", JSON.stringify(user));
      return { success: true };
    }
    return { success: false, message: "Invalid Admin credentials (Demo: admin / admin123)" };
  };

  const loginDriver = (username, password) => {
    const u = username.trim().toLowerCase();
    const p = password.trim();

    // Check against registered vehicles
    const matched = registeredVehicles.find(v => 
      v.username.toLowerCase() === u && v.password === p
    );

    if (matched) {
      const user = {
        role: "driver",
        name: matched.driver_name,
        vehicleId: matched.vehicle_id,
        vehicleType: matched.vehicle_type
      };
      setCurrentUser(user);
      localStorage.setItem("safeway_user", JSON.stringify(user));
      return { success: true, vehicle: matched };
    }

    return { 
      success: false, 
      message: "Vehicle credentials not recognized. Please use credentials generated by Admin." 
    };
  };

  const logout = () => {
    setCurrentUser(null);
    localStorage.removeItem("safeway_user");
  };

  return (
    <RoleContext.Provider value={{
      currentUser,
      loginAdmin,
      loginDriver,
      logout,
      registeredVehicles,
      setRegisteredVehicles,
      isAdmin: currentUser?.role === "admin",
      isDriver: currentUser?.role === "driver"
    }}>
      {children}
    </RoleContext.Provider>
  );
}

export const useRole = () => useContext(RoleContext);
